# Generated by Django 2.0.13 on 2019-07-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190711_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cesvpastmatchs',
        ),
    ]
