# Generated by Django 2.0.13 on 2019-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesvpastmatchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Left_team_title', models.CharField(max_length=50)),
                ('Moneybet_for_left_team', models.CharField(max_length=50)),
                ('Score', models.CharField(max_length=50)),
                ('Right_team_title', models.CharField(max_length=50)),
                ('Moneybet_for_right_team', models.CharField(max_length=50)),
                ('Hypothesis', models.CharField(max_length=50)),
            ],
        ),
    ]
